- name: Install Python
  raw: yum -y install python

- name: Install epel-release repository if not already installe
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive