---
- include_vars: private.yml

- name: Check if .my.cnf file already exists.
  stat: path=/etc/my.cnf.d
  register: mycnf_file



# 'localhost' needs to be the last item for idempotency, see
# http://docs.ansible.com/mysql_user_module.html
- name: Update MySQL root password for all root accounts.
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  template: src=dot_my.cnf.j2 dest=/etc/my.cnf.d/my.cnf mode=0600

