---
# tasks file for mariadb

- include: base.yml tags=base

- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python
    - libselinux-python
  tags:
    - database
    

- name: Ensure MariaDB is started and enabled on boot
  service: name=mariadb state=started enabled=yes
  tags:
    - database

- include: install.yml tags=database
- include: crontab.yml
